### ISSUE TITLE
Docker volume configuration

### ISSUE THREAD

**Issue by Binternet** [pelias/dockerfiles#60]
Not sure if this is a pelias or a docker issue, but in `docker-compose.yml` file you can see:

```
version: '2'
networks:
  pelias:
    driver: bridge
volumes:
  libpostaldata:   <-- what's the real path?
    driver: local
    ...
```

And in the configuration you can see reference to `libpostaldata` but I cannot understand where is the actual absolute path that is defined as `libpostaldata` on the host machine.
